### ISSUE TITLE
Support for character-footprint-particle?

### ISSUE THREAD

**Issue by Higgs1** [Penguin-Spy/skins-factored#3]
How may one modify the footprints?

Previous code https://gitlab.com/lexxyfox/factorio-wickerbeast-des/blob/fork-spaaaace/prototypes/wickerbeast_character.lua#L14-L37

Thank you

**Comment by Penguin-Spy** [comment]
added in 1.2.1 (c371d02), along with specifying the light of the character. see the usage section of the readme for how to specify the properties.
